[package]
name = "my-password-cli"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
my-password = { version = "0.1", path = "../my_password" }
docopt = "0.8.1"
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "my-password"
path = "src/main.rs"
